### ISSUE TITLE
Erreur dans URL vers descriptif d'une variable

### ISSUE THREAD

**Issue by canarduck** [pachevalier/documentation_sirene#1]
Bonjour,

Merci de cette extraction de la définition des champs sirene.

Petit bug : il y a un underscore avant les noms des variables qui casse les liens vers les pages descriptives présents dans la colonne "URL" du tableau, `/sirene/public/variable/_siren` devrait pointer sur `/sirene/public/variable/siren`.

**Comment by pachevalier** [comment]
Bien vu. C'est mis à jour. 

J'avais créé la doc pour le hackathon et je ne l'avais pas mise à jour.
